[package]
name = "compiler_core"
version = "0.1.0"
edition.workspace = true
license.workspace = true
authors.workspace = true
description = "Core compiler session management and orchestration"

[dependencies]
frontend = { path = "../frontend" }
string-interner.workspace = true
