[package]
name = "frontend"
version = "0.1.0"
authors = ["Shuzo Kashihara <suma@users.sourceforge.jp>"]
edition = "2021"
license = "MIT"
description = "Compiler front-end library"
build = "build.rs"

[dependencies]

[build-dependencies]
failure = "0.1.5"
rflex = "0.6"
