//! DROP-GLUE: synthesized per-type recursive drop functions.
//!
//! A binding whose type (transitively) contains a `Drop`-impl type
//! must free everything it owns when it dies: for the stdlib
//! containers `Box<T>` / `Vec<T>` the heap slots themselves, for
//! structs the fields, for enums the active variant's payloads.
//! Then the type's user `drop()` body runs — which for the
//! containers frees the storage the contents lived in.
//!
//! The recursion is *value*-recursive (`Box<List>` -> `List` ->
//! `Box<List>`), so it cannot be inlined at drop sites — the type
//! graph is cyclic. It lives in one synthesized function per
//! monomorphised type, generated by `FunctionLower::lower_drop_glue`
//! and called from drop sites (and from each other) at runtime.
//! The recursion depth is therefore bounded by the value's depth,
//! not the type graph — a long boxed linked list recurses one
//! frame per node, the same way Rust's own drop glue does.
//!
//! `free` is idempotent on every backend, so a value reachable
//! from several bindings (aliasing, a `get()` copy, a shared boxed
//! node) is freed once and later visits are no-ops.

use super::FunctionLower;
use crate::ir::{BinOp, Const, FuncId, InstKind, LocalId, Terminator, Type, ValueId};

/// One queued glue-function body awaiting synthesis. `ensure_drop_glue`
/// declares the function and enqueues it; the program-level driver
/// drains the queue after the source-function passes complete
/// (glue functions can request further glue functions, so the drain
/// loops until empty).
#[derive(Debug, Clone)]
pub(crate) struct GlueWork {
    pub(crate) ty: Type,
    pub(crate) func_id: FuncId,
}

impl<'a> FunctionLower<'a> {
    /// Memoized per-type drop-glue function. Returns the existing
    /// `FuncId` or declares a fresh anonymous function (signature =
    /// the type's flattened leaf locals, unit return) and queues its
    /// body for synthesis.
    pub(crate) fn ensure_drop_glue(&mut self, ty: Type) -> Result<FuncId, String> {
        if let Some(id) = self.module.drop_glue.get(&ty).copied() {
            return Ok(id);
        }
        let params = self.drop_glue_signature(ty)?;
        let n = self.module.drop_glue.len();
        let func_id = self.module.declare_function_anon(
            format!("toy_drop_glue_{n}"),
            crate::ir::Linkage::Local,
            params,
            Type::Unit,
        );
        self.module.drop_glue.insert(ty, func_id);
        // TEST-PERF: queued body-bearing glue — not plain work.
        self.scheduled.insert(func_id);
        self.pending_glue_work.push(GlueWork { ty, func_id });
        Ok(func_id)
    }

    /// The flattened leaf types of `ty` — the parameter list of its
    /// glue function, in the same order `collect_leaves` / the
    /// function-boundary flattening use (local `i` ↔ leaf `i`).
    fn drop_glue_signature(&self, ty: Type) -> Result<Vec<Type>, String> {
        match ty {
            Type::Struct(struct_id) => {
                let def = self.module.struct_def(struct_id);
                let mut out = Vec::new();
                for (_, ft) in &def.fields {
                    out.extend(self.drop_glue_signature(*ft)?);
                }
                Ok(out)
            }
            // Tag, then every variant's payloads in declaration order
            // — the same layout `collect_leaves` uses for an enum in
            // a heap slot.
            Type::Enum(enum_id) => {
                let def = self.module.enum_def(enum_id);
                let mut out = vec![Type::U64];
                for variant in &def.variants {
                    for pt in &variant.payload_types {
                        out.extend(self.drop_glue_signature(*pt)?);
                    }
                }
                Ok(out)
            }
            Type::Tuple(tuple_id) => {
                let mut out = Vec::new();
                for t in &self.module.tuple_defs[tuple_id.0 as usize] {
                    out.extend(self.drop_glue_signature(*t)?);
                }
                Ok(out)
            }
            scalar @ (Type::I64
            | Type::U64
            | Type::F64
            | Type::Bool
            | Type::Str
            | Type::I8
            | Type::U8
            | Type::I16
            | Type::U16
            | Type::I32
            | Type::U32) => Ok(vec![scalar]),
            other => Err(format!(
                "drop glue: unsupported leaf type {}",
                crate::spelling::spell_type(self.module, self.interner, other)
            )),
        }
    }

    /// Whether a value of `ty` owns resources — the type itself has a
    /// `Drop` impl, or it holds one by value. This is the IR-side
    /// mirror of the frontend's `DropAnalysis::contains_drop`; the
    /// walk short-circuits at any `Drop`-impl type, and every cycle
    /// in the type graph passes through one (`Box` / `Vec`), so the
    /// recursion terminates.
    pub(crate) fn ir_contains_drop(&self, ty: Type) -> bool {
        match ty {
            Type::Struct(struct_id) => {
                let def = self.module.struct_def(struct_id);
                if self.module.drop_trait_structs.contains(&def.base_name) {
                    return true;
                }
                def.fields
                    .iter()
                    .any(|(_, ft)| self.ir_contains_drop(*ft))
            }
            Type::Enum(enum_id) => {
                let def = self.module.enum_def(enum_id);
                if self.module.drop_trait_structs.contains(&def.base_name) {
                    return true;
                }
                def.variants
                    .iter()
                    .any(|v| v.payload_types.iter().any(|pt| self.ir_contains_drop(*pt)))
            }
            Type::Tuple(tuple_id) => self.module.tuple_defs[tuple_id.0 as usize]
                .iter()
                .any(|t| self.ir_contains_drop(*t)),
            _ => false,
        }
    }

    /// Synthesize the body of one queued glue function: the recursive
    /// free of everything a value of `work.ty` owns, followed (for
    /// `Drop`-impl types) by the user `drop()` call.
    pub(crate) fn lower_drop_glue(&mut self, work: &GlueWork) -> Result<(), String> {
        // Declare the parameter locals: `LocalId(i)` ↔ leaf `i` in
        // declaration order (codegen binds `block_params[i]` to
        // `locals[i]`, so every param must exist in `func.locals`).
        let params = self.module.function(self.func_id).params.clone();
        for t in &params {
            self.module.function_mut(self.func_id).add_local(*t);
        }
        let entry = self.module.function_mut(self.func_id).add_block();
        self.module.function_mut(self.func_id).entry = entry;
        self.current_block = Some(entry);
        match work.ty {
            Type::Struct(struct_id) => self.glue_struct_value(struct_id)?,
            Type::Enum(enum_id) => self.glue_enum_value(enum_id)?,
            Type::Tuple(tuple_id) => self.glue_tuple_value(tuple_id)?,
            // Primitives own nothing; the glue is an empty function.
            _ => {}
        }
        if self.current_block.is_some() {
            self.terminate(Terminator::Return(Vec::new()));
        }
        Ok(())
    }

    /// The glue function's parameter locals: `LocalId(i)` ↔ leaf `i`.
    fn glue_param_locals(&self) -> Vec<(LocalId, Type)> {
        self.module
            .function(self.func_id)
            .params
            .iter()
            .enumerate()
            .map(|(i, t)| (LocalId(i as u32), *t))
            .collect()
    }

    /// Glue for a struct value.
    ///
    /// - `Box<T>`: glue the slot's contents (read per-leaf via
    ///   `PtrRead`, then recurse), then run the user drop (frees the
    ///   slot).
    /// - `Vec<T>`: glue every element (runtime loop over `len`, each
    ///   element read per-leaf at `data + i * elem_size`), then run
    ///   the user drop (frees the buffer).
    /// - A `Drop`-impl struct: run the user drop first (Rust order —
    ///   the body may read its fields), then glue each field that
    ///   contains resources.
    /// - Any other struct: glue each field that contains resources.
    fn glue_struct_value(&mut self, struct_id: crate::ir::StructId) -> Result<(), String> {
        let def = self.module.struct_def(struct_id).clone();
        let base = def.base_name;
        let all_locals = self.glue_param_locals();

        if self.interner.resolve(base) == Some("Box") {
            return self.glue_box_contents(struct_id, &def, &all_locals);
        }
        if self.interner.resolve(base) == Some("Vec") {
            return self.glue_vec_elements(struct_id, &def, &all_locals, false);
        }
        // DATA-ORIENTED Phase 2: `SoaVec<T>` holds the same four
        // fields and owns its elements the same way — only where a
        // leaf lives differs, so the walk is shared.
        if self.interner.resolve(base) == Some("SoaVec") {
            return self.glue_vec_elements(struct_id, &def, &all_locals, true);
        }
        if self.module.drop_trait_structs.contains(&base) {
            self.emit_user_drop_for_struct(struct_id, &all_locals)?;
        }
        let mut offset = 0usize;
        for (_, ft) in &def.fields {
            offset = self.emit_leaf_glue(*ft, offset)?;
        }
        Ok(())
    }

    /// Box contents: read the slot as `type_args[0]` (per-leaf) and
    /// recurse, then free the slot via the user drop.
    fn glue_box_contents(
        &mut self,
        struct_id: crate::ir::StructId,
        def: &crate::ir::StructDef,
        all_locals: &[(LocalId, Type)],
    ) -> Result<(), String> {
        let elem_ty = *def
            .type_args
            .first()
            .ok_or_else(|| "drop glue: Box has no type argument".to_string())?;
        let leaves = self
            .compute_leaf_layout(elem_ty)
            .ok_or_else(|| {
                format!(
                    "drop glue: no leaf layout for boxed {}",
                    crate::spelling::spell_type(self.module, self.interner, elem_ty)
                )
            })?;
        let data_local = all_locals
            .first()
            .map(|(l, _)| *l)
            .ok_or_else(|| "drop glue: Box has no data field".to_string())?;
        let data_v = self
            .emit(InstKind::LoadLocal(data_local), Some(Type::U64))
            .ok_or_else(|| "drop glue: box data LoadLocal returned no value".to_string())?;
        let mut read_vals: Vec<ValueId> = Vec::with_capacity(leaves.len());
        for (leaf_off, leaf_ty) in leaves {
            let off_v = self
                .emit(
                    InstKind::Const(Const::U64(leaf_off)),
                    Some(Type::U64),
                )
                .ok_or_else(|| "drop glue: box leaf offset Const returned no value".to_string())?;
            let v = self
                .emit(
                    InstKind::PtrRead {
                        ptr: data_v,
                        offset: off_v,
                        elem_ty: leaf_ty,
                    },
                    Some(leaf_ty),
                )
                .ok_or_else(|| "drop glue: box PtrRead returned no value".to_string())?;
            read_vals.push(v);
        }
        let glue_id = self.ensure_drop_glue(elem_ty)?;
        self.emit(InstKind::Call { target: glue_id, args: read_vals }, None);
        self.emit_user_drop_for_struct(struct_id, all_locals)
    }

    /// Vec elements: iterate `data[i * elem_size]` for `i in
    /// 0..len`, reading each element per-leaf, recursing into each,
    /// then free the buffer via the user drop.
    ///
    /// With `soa` set the buffer is `SoaVec<T>`'s column split
    /// instead, so leaf `j` of element `i` is read from
    /// `prefix_j * cap + i * stride_j` (DATA-ORIENTED Phase 2). The
    /// loop, the recursion and the final free are identical — an
    /// owning element must be released wherever it is stored.
    fn glue_vec_elements(
        &mut self,
        struct_id: crate::ir::StructId,
        def: &crate::ir::StructDef,
        all_locals: &[(LocalId, Type)],
        soa: bool,
    ) -> Result<(), String> {
        let elem_ty = *def
            .type_args
            .first()
            .ok_or_else(|| "drop glue: Vec has no type argument".to_string())?;
        let columns = self
            .soa_columns(elem_ty)
            .ok_or_else(|| {
                format!(
                    "drop glue: no leaf layout for vec element {}",
                    crate::spelling::spell_type(self.module, self.interner, elem_ty)
                )
            })?;
        // Locals: 0 = data, 1 = len, 2 = cap, 3 = elem_size (field
        // declaration order — `Vec { data, len, cap, elem_size }`).
        let data_local = *all_locals
            .first()
            .ok_or_else(|| "drop glue: Vec has no data field".to_string())?;
        let len_local = *all_locals
            .get(1)
            .ok_or_else(|| "drop glue: Vec has no len field".to_string())?;
        let elem_size_local = *all_locals
            .get(3)
            .ok_or_else(|| "drop glue: Vec has no elem_size field".to_string())?;
        let cap_local = *all_locals
            .get(2)
            .ok_or_else(|| "drop glue: Vec has no cap field".to_string())?;
        let data_v = self
            .emit(InstKind::LoadLocal(data_local.0), Some(Type::U64))
            .ok_or_else(|| "drop glue: vec data LoadLocal returned no value".to_string())?;
        let len_v = self
            .emit(InstKind::LoadLocal(len_local.0), Some(Type::U64))
            .ok_or_else(|| "drop glue: vec len LoadLocal returned no value".to_string())?;
        let elem_size_v = self
            .emit(InstKind::LoadLocal(elem_size_local.0), Some(Type::U64))
            .ok_or_else(|| "drop glue: vec elem_size LoadLocal returned no value".to_string())?;
        let cap_v = self
            .emit(InstKind::LoadLocal(cap_local.0), Some(Type::U64))
            .ok_or_else(|| "drop glue: vec cap LoadLocal returned no value".to_string())?;

        // i = 0; loop header: i < len ?
        let i_local = self.module.function_mut(self.func_id).add_local(Type::U64);
        let zero = self
            .emit(InstKind::Const(Const::U64(0)), Some(Type::U64))
            .ok_or_else(|| "drop glue: vec index Const returned no value".to_string())?;
        self.emit(InstKind::StoreLocal { dst: i_local, src: zero }, None);
        let header = self.fresh_block();
        let body = self.fresh_block();
        let exit = self.fresh_block();
        self.terminate(Terminator::Jump(header));
        self.switch_to(header);
        let i_v = self
            .emit(InstKind::LoadLocal(i_local), Some(Type::U64))
            .ok_or_else(|| "drop glue: vec index LoadLocal returned no value".to_string())?;
        let cmp = self
            .emit(
                InstKind::BinOp {
                    op: BinOp::Lt,
                    lhs: i_v,
                    rhs: len_v,
                },
                Some(Type::Bool),
            )
            .ok_or_else(|| "drop glue: vec loop compare returned no value".to_string())?;
        self.terminate(Terminator::Branch {
            cond: cmp,
            then_blk: body,
            else_blk: exit,
        });

        self.switch_to(body);
        let glue_id = self.ensure_drop_glue(elem_ty)?;
        let address = if soa {
            crate::soa::BufferAddress::Columns { index: i_v, cap: cap_v }
        } else {
            let base_off = self
                .emit(
                    InstKind::BinOp {
                        op: BinOp::Mul,
                        lhs: i_v,
                        rhs: elem_size_v,
                    },
                    Some(Type::U64),
                )
                .ok_or_else(|| "drop glue: vec element offset Mul returned no value".to_string())?;
            crate::soa::BufferAddress::Interleaved { base: base_off }
        };
        let mut read_vals: Vec<ValueId> = Vec::with_capacity(columns.len());
        for column in &columns {
            let off_v = self.emit_leaf_offset(&address, column);
            let v = self
                .emit(
                    InstKind::PtrRead {
                        ptr: data_v,
                        offset: off_v,
                        elem_ty: column.2,
                    },
                    Some(column.2),
                )
                .ok_or_else(|| "drop glue: vec element PtrRead returned no value".to_string())?;
            read_vals.push(v);
        }
        self.emit(InstKind::Call { target: glue_id, args: read_vals }, None);
        // i += 1; back edge.
        let one = self
            .emit(InstKind::Const(Const::U64(1)), Some(Type::U64))
            .ok_or_else(|| "drop glue: vec step Const returned no value".to_string())?;
        let next = self
            .emit(
                InstKind::BinOp {
                    op: BinOp::Add,
                    lhs: i_v,
                    rhs: one,
                },
                Some(Type::U64),
            )
            .ok_or_else(|| "drop glue: vec step Add returned no value".to_string())?;
        self.emit(InstKind::StoreLocal { dst: i_local, src: next }, None);
        self.terminate(Terminator::Jump(header));
        self.switch_to(exit);

        self.emit_user_drop_for_struct(struct_id, all_locals)
    }

    /// Emit the glue call for a sub-value of type `ty` whose leaves
    /// start at local `offset`. Returns the next free local offset.
    fn emit_leaf_glue(&mut self, ty: Type, offset: usize) -> Result<usize, String> {
        let leaf_tys = self.drop_glue_signature(ty)?;
        if self.ir_contains_drop(ty) {
            let glue_id = self.ensure_drop_glue(ty)?;
            let mut args: Vec<ValueId> = Vec::with_capacity(leaf_tys.len());
            for (i, lt) in leaf_tys.iter().enumerate() {
                let local = LocalId((offset + i) as u32);
                let v = self
                    .emit(InstKind::LoadLocal(local), Some(*lt))
                    .ok_or_else(|| "drop glue: leaf LoadLocal returned no value".to_string())?;
                args.push(v);
            }
            self.emit(InstKind::Call { target: glue_id, args }, None);
        }
        Ok(offset + leaf_tys.len())
    }

    /// Glue for an enum value: dispatch on the tag, then glue the
    /// active variant's payloads.
    fn glue_enum_value(&mut self, enum_id: crate::ir::EnumId) -> Result<(), String> {
        let def = self.module.enum_def(enum_id).clone();
        if def.variants.is_empty() {
            return Ok(());
        }
        let tag_v = self
            .emit(InstKind::LoadLocal(LocalId(0)), Some(Type::U64))
            .ok_or_else(|| "drop glue: enum tag LoadLocal returned no value".to_string())?;
        let end = self.fresh_block();
        // Per-variant payload leaf ranges, in declaration order.
        let mut variant_ranges: Vec<Vec<(usize, usize)>> = Vec::with_capacity(def.variants.len());
        let mut offset = 1usize;
        for variant in &def.variants {
            let mut ranges = Vec::with_capacity(variant.payload_types.len());
            for pt in &variant.payload_types {
                let count = self.drop_glue_signature(*pt)?.len();
                ranges.push((offset, offset + count));
                offset += count;
            }
            variant_ranges.push(ranges);
        }
        let mut check = self.current_block.expect("entry block must exist");
        for (vi, ranges) in variant_ranges.iter().enumerate() {
            if vi > 0 {
                self.switch_to(check);
            }
            let body = self.fresh_block();
            let fallthrough = self.fresh_block();
            let tag_cmp = self
                .emit(
                    InstKind::Const(Const::U64(vi as u64)),
                    Some(Type::U64),
                )
                .ok_or_else(|| "drop glue: variant index Const returned no value".to_string())?;
            let eq = self
                .emit(
                    InstKind::BinOp {
                        op: BinOp::Eq,
                        lhs: tag_v,
                        rhs: tag_cmp,
                    },
                    Some(Type::Bool),
                )
                .ok_or_else(|| "drop glue: variant compare returned no value".to_string())?;
            self.terminate(Terminator::Branch {
                cond: eq,
                then_blk: body,
                else_blk: fallthrough,
            });
            self.switch_to(body);
            for (range, pt) in ranges.iter().zip(def.variants[vi].payload_types.iter()) {
                if self.ir_contains_drop(*pt) {
                    let glue_id = self.ensure_drop_glue(*pt)?;
                    let leaf_tys = self.drop_glue_signature(*pt)?;
                    let mut args: Vec<ValueId> = Vec::with_capacity(range.1 - range.0);
                    for (i, lt) in leaf_tys.iter().enumerate() {
                        let v = self
                            .emit(
                                InstKind::LoadLocal(LocalId((range.0 + i) as u32)),
                                Some(*lt),
                            )
                            .ok_or_else(|| {
                                "drop glue: payload LoadLocal returned no value".to_string()
                            })?;
                        args.push(v);
                    }
                    self.emit(InstKind::Call { target: glue_id, args }, None);
                }
            }
            self.terminate(Terminator::Jump(end));
            check = fallthrough;
        }
        // A tag outside every variant is unreachable; fall through.
        self.switch_to(check);
        self.terminate(Terminator::Jump(end));
        self.switch_to(end);
        Ok(())
    }

    /// Glue for a tuple value: recurse into each element that owns
    /// resources.
    fn glue_tuple_value(&mut self, tuple_id: crate::ir::TupleId) -> Result<(), String> {
        let elems = self.module.tuple_defs[tuple_id.0 as usize].clone();
        let mut offset = 0usize;
        for et in &elems {
            offset = self.emit_leaf_glue(*et, offset)?;
        }
        Ok(())
    }

    /// Emit the user `drop()` call for a struct value whose leaves
    /// live at `locals` (receiver + writeback dests — same shape as
    /// the old auto-drop call).
    pub(crate) fn emit_user_drop_for_struct(
        &mut self,
        struct_id: crate::ir::StructId,
        locals: &[(LocalId, Type)],
    ) -> Result<(), String> {
        let struct_def = self.module.struct_def(struct_id);
        let struct_sym = struct_def.base_name;
        let drop_sym = match self.interner.get("drop") {
            Some(s) => s,
            None => return Err("auto-drop: `drop` symbol missing from interner".to_string()),
        };
        let type_args: Vec<Type> = struct_def.type_args.clone();
        let func_id = match super::method_registry::resolve_method_target(
            self.method_func_ids,
            self.generic_methods,
            struct_sym,
            drop_sym,
            &type_args,
        ) {
            Some(super::method_registry::ResolvedMethodTarget::Concrete(id)) => id,
            Some(super::method_registry::ResolvedMethodTarget::Template(t)) => {
                self.instantiate_generic_method_with_args(
                    struct_sym, drop_sym, &t, struct_id, &[],
                )
                .map_err(|e| {
                    format!(
                        "auto-drop: failed to instantiate Drop for `{}`: {e}",
                        self.interner.resolve(struct_sym).unwrap_or("?")
                    )
                })?
            }
            None => {
                let s = self.interner.resolve(struct_sym).unwrap_or("?");
                return Err(format!(
                    "auto-drop: no `drop` FuncId registered for struct `{s}`"
                ));
            }
        };
        // CODE-SIZE-SELF-ABI: `drop` is a `&mut self` method like any
        // other, so a wide struct's `drop` takes its receiver as a
        // pointer. Glue runs over leaf locals it was handed, so it
        // materialises a slot the same way an ordinary call site does
        // -- and reads nothing back, since the value is being dropped.
        let mut args: Vec<ValueId> = Vec::with_capacity(locals.len());
        let mut self_dests: Vec<LocalId> = Vec::with_capacity(locals.len());
        if self.module.function(func_id).ptr_self().is_some() {
            let (addr, reload) = self.receiver_address(locals)?;
            args.push(addr);
            // The value is being destroyed; nothing reads it back.
            reload.skip();
        } else {
            for (local, ty) in locals {
                let v = self
                    .emit(InstKind::LoadLocal(*local), Some(*ty))
                    .ok_or_else(|| "auto-drop: LoadLocal returned no value".to_string())?;
                args.push(v);
                self_dests.push(*local);
            }
        }
        self.emit(
            InstKind::CallWithSelfWriteback {
                target: func_id,
                args,
                ret_dest: None,
                ret_ty: None,
                self_dests,
            },
            None,
        );
        Ok(())
    }
}
